### ISSUE TITLE
Highlights page

### ISSUE THREAD

**Issue by antondtran** [Cascadia-Mobile-App-Projects/YUP253#10]
Create a highlights page for users to view highlights

DoD: Highlights page allows user to post, view, edit, and delete text.

**Comment by MikeTheGreat** [comment]
Highlights should be drawn from the DB (talk to Jason about getting the data repository to support this)

**Comment by MikeTheGreat** [comment]
Ok to do only text highlights for Sprint 3; definitely want to have images and/or videos for Sprint 4
