### ISSUE TITLE
Login View/Create Account View

### ISSUE THREAD

**Issue by antondtran** [Cascadia-Mobile-App-Projects/YUP253#33]
Login View that takes in user input for username and password. If user name or password is incorrect, an error message will be displayed. Otherwise login will be successful. Login view should be displayed upon app launch. Create account option should be displayed on login view.

**Comment by MikeTheGreat** [comment]
Also for this task - on app startup, show only the login page (after showing the splash page, which is handled by Sean), then remove login page from tabbar at bottom of main screen.

**Comment by MikeTheGreat** [comment]
For now - use hard coded username & password (s)
